### ISSUE TITLE
Move content of old saros page to GitHub pages

### ISSUE THREAD

**Issue by m273d15** [saros-project/saros#111]
The content of the following files has to be moved potentially in the structure of the new pages.

**Move the content only if**:
* The content is out-dated AND has to be substituted with an up-to-date version
* The content is really related to saros AND relevant for an user or developer

**Don't migrate tutorials of other tools into the new site**
Rather reference the official documentation / another tutorial. e,g, EGit already has a very detailed documentation. There is no reason to maintain an own documentation. 

See here for an [archive with already converted pages](https://github.com/saros-project/saros/files/2163438/old_saros_page.tar.gz)

Files:
- [X] old/sonarqube-gerrit-bridge.md (**Not migrated**, reason: obsolete)
- [X] old/contact.md (to support page)
- [X] old/archnemesis.md (**Not migrated**, reason: obsolete)
- [X] old/node/28.md
- [X] old/home.md
- [X] old/bugtracker.md (duplicate of `old/node/28.md`)
- [X] old/install-subclipse.md (**Not migrated**, reason: obsolete)
- [X] old/tools.md (**Not migrated**, reason: obsolete)
- [X] old/sia.md (**Not migrated**, reason: obsolete)
- [X] old/eclipse-setup-ssh.md (**Not migrated**, reason: obsolete)
- [X] old/git-recipes.md (**Not migrated**, Rewrite, reason: obsolete)
- [X] old/guidelines.md
- [X] old/jenkins.md (**Not migrated**, Rewrite, reason: obsolete)
- [X] old/documentation.md (**Not migrated**, Rewrite, reason: obsolete)
- [X] old/host-comic.md
- [X] old/install-egit.md (**Not migrated**, Should be substituted with a link to the egit documentation)
- [X] old/ci-rules.md (**Not migrated**, Rewrite, reason: obsolete)
- [X] old/index.md
- [X] old/checkout-and-first-steps.md (**Not migrated**, Rewrite, reason: just an overview page)
- [X] old/build-server-migration.md (**Not migrated**, reason: obsolete)
- [X] old/mailing-list-chat.md
- [X] old/TicketGuidelines.md (**Not migrated**, reason: obsolete)
- [X] old/support_home.md
- [X] old/relatedwork.md (**Not migrated**, reason: superfluous)
- [X] old/review.md
- [X] old/ReleaseProcess.md
- [X] old/coderules.1.md (in pr #195)
- [X] old/usability.md (in pr #195)
- [X] old/import-code-style-profiles.md (in pr #195)
- [X] old/contribution.md (in pr #195)
- [X] old/coderules.md (in pr #195)
- [X] old/bibliography.md (**Not migrated**)
- [x] old/commit-and-push-first-change.md
- [x] old/stf-cross-ide.md (Move into GitHub issues if something is still up-to-date)
- [x] old/node/150.md
- [x] old/node/160.md
- [x] old/node/144.md
- [x] old/node/22.md
- [x] old/node/179.md
- [x] old/node/126.md
- [x] old/node/189.md
- [x] old/node/39.md
- [x] old/node/155.md
- [x] old/node/149.md
- [x] old/node/16.md
- [x] old/node/166.md
- [x] old/node/146.md
- [x] old/node/121.md
- [x] old/node/154.md
- [x] old/node/60.md
- [x] old/node/168.md
- [x] old/node/18.md
- [x] old/node/163.md
- [x] old/node/178.md
- [x] old/node/167.md
- [x] old/node/159.md
- [x] old/node/21.md
- [x] old/node/170.md
- [x] old/node/129.md
- [x] old/node/44.md
- [x] old/node/148.md
- [x] old/node/122.md
- [x] old/node/147.md
- [x] old/node/19.md
- [x] old/node/142.md
- [x] old/node/157.md
- [x] old/node/128.md
- [x] old/node/15.md
- [x] old/node/153.md
- [x] old/node/27.md
- [x] old/node/138.md
- [x] old/node/130.md
- [x] old/node/152.md
- [x] old/node/25.md
- [x] old/node/70.md
- [x] old/node/140.md
- [x] old/node/125.md
- [x] old/node/20.md
- [x] old/node/139.md
- [x] old/node/177.md
- [x] old/node/158.md
- [x] old/componentsRunningSession.md
- [x] old/sessionManagement.md
- [x] old/gsoc.1.md
- [x] old/techdoc.md
- [x] old/activitySending.md
- [x] old/html-gui.md
- [x] old/userStates.md
- [x] old/research.md (**Not migrated**)
- [x] old/saros-for-intellij/plan.md
- [x] old/saros-for-intellij/local-testing.md
- [x] old/saros-for-intellij/dev-environment.md
- [x] old/activities.md
- [x] old/feedback.md
- [x] old/architectureDocumentation.md
- [x] old/sharedsession.md
- [x] old/eclipsebridge.md
- [x] old/make-first-change.md
- [x] old/concurrency.md
- [x] old/ui.md
- [x] old/processes.md
- [x] old/sessionNegotiation.md
- [x] old/get-source-code.md
- [x] old/packageFeedback.md, old/node/20.md, old/feedback.md
- [x] old/ongoing-work.md
- [x] old/jtourbus.md
- [x] old/intellij-tips.md
- [x] old/eclipse-setup-git.md
- [x] old/networklayer.md
- [x] old/mailingslists.md
- [x] old/dev-environment-reqs.md
- [x] old/specoverview.md
- [x] old/our-dev-workflow.md
- [x] old/testing.md
- [x] old/gsoc.md
- [x] old/upload-new-patch-set.md (Substitute with a link to Git basics)
- [x] old/projectNegotiation.md
- [x] old/build-sarosnetbeans-just-with-ant.md
- [x] old/invitation.md
- [x] old/getinvolved.md
- [x] old/run-saros-as-dev.md
- [x] old/setup-dev-environment.md
- [x] old/componentsInvitationProcess.md
- [x] old/setup-netbeans-environment.md
- [x] old/gsoc/2015/ideas.md
- [x] old/developerdoc.md

**Comment by chrismotian** [comment]
It would be nice if the saros-project.org website would give you a hint that the old review process with Gerrit is outdated and we use Github now. It takes me too long to find that out by myself.

**Comment by m273d15** [comment]
I moved the most important content into the [move_documentation](/saros-project/saros/tree/move_documentation) branch. I will restructurize the content and create a PR. The next step will be the rework of the content.
