### ISSUE TITLE
Add XStream security framework setup

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#209]
XStream 1.4.7 and above include a security framework that can be used to white-list certain actions. Such a security framework should be set up to prevent exploits using XStream. More details about the issue are given on the XStream security page: http://x-stream.github.io/security.html

Details (as well as an example) on how to configure the security framework are given in the section http://x-stream.github.io/security.html#framework

To correctly configure this white-list, we will first have to determine the minimal set of permissions need for our use case.

Our XStream provider is defined in the core: [saros/misc/xstream/XStreamExtensionProvider](https://github.com/saros-project/saros/blob/master/core/src/saros/misc/xstream/XStreamExtensionProvider.java)

### XStream version compatibility
We have to ensure that all Saros versions are using compatible XStream versions.

Saros/I is currently relying on the XStream version supplied by IntelliJ (XStream 1.4.10 since IntelliJ 2018.2) as the version contained in the core does not seem to be compatible with Java 8.

The core is currently using a snapshot version of XStream: xstream-1.4-20101008.163445-1.jar
I am not sure which minor release it is, but it is probably a snapshot of the 1.4 development branch as the version 1.4 was released in August 2011 and this name of the snapshot suggests that it is from October 2010. I am not sure whether there is a reason to use this snapshot or if an update would break stuff.

As we are currently working towards moving all Saros components to Java 8, I would suggest to update the XStream version of the core to a proper release above 1.4.7. But I am not sure whether XStream 1.4.7 and above still support Java 6.

### TODOs
- [x] determine XStream version compatibility
  - [x] update the XStream library contained in the core if necessary
- [x] determine the minimal set of needed permissions
- [x] add the security manager setup to the [XStreamExtensionProvider](https://github.com/saros-project/saros/blob/master/core/src/saros/misc/xstream/XStreamExtensionProvider.java)

**Comment by srossbach** [comment]
I do not see any point to setup some security stuff. XStream should be used as a marshalling instance and not as serializer, i.e map complex types / objects to simple types like strings and integers.

Furthermore Saros itself is more dangerous, you can just execute delete operation on files.

And finally, the rule of all rules: Do not trust the client a.k.a check and verify the data you receive.

So there is mainly only one point left: does XStream work with Java 8 ? I do not have Java 8 installed but I guess many developers have and I still not have received a single complain that Saros do not work when using a Java 8 JRE/JDK (of course it is compiled with a different version).

**Comment by tobous** [comment]
This security framework defines which classes can be unmarshaled using XStream. I don't think it hurts to use it, but I haven't really read up on the topic to present a strong argument. I would assume that it protects us against exploits when unmarshaling the data. I am not sure how we should effectively check/verify the data we receive before unmarshaling it. (Furthermore, XStream will clog up our logs with warnings if we don't set up the security framework.)

I had a go at adding a minimal set of permissions for Saros/I. I am not really familiar with all that stuff, so I just allowed all classes tagged with `XStreamAlias`.

```Java
        //clear all existing permissions
        xstream.addPermission(NoTypePermission.NONE);

        //allow all classes inheriting from/implementing these classes
        xstream.allowTypeHierarchy(Operation.class);
        xstream.allowTypeHierarchy(IActivity.class);
        xstream.allowTypeHierarchy(SarosPacketExtension.class);

        Class[] allowedClasses = { String.class, Map.class,
                XStreamPacketExtension.class, VersionExchangeExtension.class,
                UserListExtension.UserListEntry.class,
                ProjectNegotiationData.class, JupiterVectorTime.class,
                FileList.class,

                //classes that are tagged but are not needed to start a Saros/I session
                SPath.class, TimeStamp.class, int.class, JID.class, List.class,
                MetaData.class, boolean.class, long.class };

        xstream.allowTypes(allowedClasses);

        String[] allowedClassNames = {
                "de.fu_berlin.inf.dpp.negotiation.FileList$File" };

        xstream.allowTypes(allowedClassNames);
```

Concerning the XStream Java 8 compatibility: I know I had some kind of problem with the version included in the core after switching Saros/I to the IntelliJ release 2017.3.1 (and subsequently Java 8). But I can't recreate the behavior so it might have been an interaction with another component that has since been resolved or I made a mistake.

None the less I still think using the current version of the XStream library would be preferable (independent of the Security framework stuff, which does not work with the core version). We are using way to many outdated libraries. I would assume that there were at least a few fixes for critical/important bugs and other improvements in the meantime.
