### ISSUE TITLE
Improve IResource.getAdapter(...) to return objects of the given class

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#359]
The method `IResource.getAdapter(Class<? extends IResource>)` is meant as a way to safely unwrap an IResource object to access the contained class directly instead of through the interface. This is done by internally checking whether the contained object is actually of the given type and returning null otherwise.

The problem with the current implementation is that it does not do the cast itself, meaning it still has to be done by the caller. A better solution would be to use change the return type to the given type and cast internally if possible. This change is trivial for the [IntelliJ](https://github.com/saros-project/saros/blob/master/de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/filesystem/IntelliJResourceImpl.java#L11) and [Server](https://github.com/saros-project/saros/blob/master/de.fu_berlin.inf.dpp.server/src/de/fu_berlin/inf/dpp/server/filesystem/ServerResourceImpl.java#L89) classes. The main part of the work will be adjusting the [Eclipse](https://github.com/saros-project/saros/blob/master/de.fu_berlin.inf.dpp/src/de/fu_berlin/inf/dpp/filesystem/EclipseResourceImpl.java#L128) class.

There already exist a [Gerrit patch](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3291/) for this that shows the general idea behind the change. Due to some (major) reworks in almost all touched classes, this patchset is severely outdated and should only be used as a jumping of point.

As part of this change, I would also suggest renaming the method to better reflect its actual purpose. My suggestion would be to name it `adaptTo(...)` to show that the object is adapted to the given class.

#### TODOs
- [x] Adjust IntelliJ class: [IntelliJResourceImpl](https://github.com/saros-project/saros/blob/master/de.fu_berlin.inf.dpp.intellij/src/de/fu_berlin/inf/dpp/intellij/filesystem/IntelliJResourceImpl.java#L11)
- [x] Adjust Server class: [ServerResourceImpl](https://github.com/saros-project/saros/blob/master/de.fu_berlin.inf.dpp.server/src/de/fu_berlin/inf/dpp/server/filesystem/ServerResourceImpl.java#L89)
- [x] Adjust Eclipse class: [EclipseResourceImpl](https://github.com/saros-project/saros/blob/master/de.fu_berlin.inf.dpp/src/de/fu_berlin/inf/dpp/filesystem/EclipseResourceImpl.java#L128)
- [x] Remove the casts from every usage of `IResource.getAdapter(...)`
- [x] Rename the method (for example to `IResource.adaptTo(...)`)
