### ISSUE TITLE
Implement Caret Listener and Caret Annotations

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#367]
Currently, Saros/I is still missing caret annotations (highlighting the caret position of other users). To realize this feature, a caret listener has to be added and the annotation feature has to be implemented.

There is already a placeholder class for a caret listener: [`StoppableCaretListener`](https://github.com/saros-project/saros/blob/master/intellij/src/saros/intellij/eventhandler/editor/caret/StoppableCaretListener.java). This class however implements the wrong interface. The correct interface to use is `com.intellij.openapi.editor.event.CaretListener`. `caretPositionChanged` is most likely the only needed method.

**Update:** This will most likely have to replace the current selection listener as the selection listener does not seem differentiate between carets (needs more testing when working on this). Instead, the caret listener should differentiate between the carets in the event handling (e.g. hold a reference to the added "Saros carets" or check if it is primary cared through `CaretModel.getPrimaryCaret()`). This can replace the selection listener as all selections also automatically include a caret location change. The selection range of the caret can then also be read and manipulated through the `Caret` object.

**Update 2:** Carets can't be used to display remote carets as they always remain controlled by the user, i.e. using the arrows will move *all* carets in the current editor (not only the primary caret). Instead, a zero-width boxed highlighting can be used to simulate the appearance of a caret.

To figure out how the caret information is transmitted to other participants, look at the Saros/E implementation.

#### TODOs
- [x] Implement a caret listener (and possible merge it with `LocalTextSelectionChangeHandler`)
  - [x] Rename `StoppableCaretListener` to match the new naming scheme (e.g. `LocalCaretChangeHandler`)
  - [x] Implement `com.intellij.openapi.editor.event.CaretListener.caretPositionChanged`
- [x] Implement caret annotations
  - [x] If possible/plausible, use the existing annotation logic ([`AbstractEditorAnnotation`](https://github.com/saros-project/saros/blob/master/intellij/src/saros/intellij/editor/annotations/AbstractEditorAnnotation.java), [`AnnotationStore`](https://github.com/saros-project/saros/blob/master/intellij/src/saros/intellij/editor/annotations/AnnotationStore.java), [`AnnotationManager`](https://github.com/saros-project/saros/blob/master/intellij/src/saros/intellij/editor/annotations/AnnotationManager.java))

**Comment by tobous** [comment]
Blocked by issue with caret listener described [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360006880480-CaretListener-caretPositionChanged-gets-called-before-selection-data-is-updated).
