### ISSUE TITLE
Preparing a new release

### ISSUE THREAD

**Issue by m273d15** [saros-project/saros#440]
* [x] Clarify version scheme (started in #351)
  * [x] #465
* [X] acceptance test of Saros/E
  * [x] Disable feedback mechanisms (#425)
  * [X] #463 (Solved by #489 and #503)
  * [X] Fix findings *(add corresponding issue numbers here)*:
    * [X] #469
* [x] Rework ColorIDSet and XMPPAccount serialization (#491)
* [x] acceptance test of Saros/I
  * [x] Fix findings *(add corresponding issue numbers here)*
* [x] acceptance test of Saros/HTML Whiteboard (will not be released)
* [ ] Write Release note and Changelog
* [X] Switch to Github Pages doc and link old documentation

**If I missed an important task or you know issues which have to be addressed before a release, please add them to this issue.**

**Comment by m273d15** [comment]
provisional changelog (I included all changes that seem to be relevant for users (UI changes and user experience changes), I excluded all HTML, Intellij changes):
```
<version>
======
[FIX] #871 Session negotiation fails due to wrong timeouts
[FIX] SarosSXETransmitter was leaking threads on dispose
[FIX][E] #90 Avoid automatically set "Only Socks5" checkbox
[FIX] #866 Creating XMPP account and configuring Saros is not possible
[FIX] #830 Switching Eclipse themes triggers exceptions when using Saros
[FIX] #875 Session startup does not prevent invitation requests
[FIX] #870 Saros view is not reflecting the current internal status
[FIX] #881 Wizards are opened in background
[FIX] roster may display wrong Saros support
[UI] remove nickname usage during OPN/IPN
[FIX] #854 Jabber ID is correct but does not validate
[FIX] prevent resource qualified JID as account JIDs
[FIX] ID:#844-Wording fixed, added Cancel button to dialog.
[FIX] UI displayed incorrect Saros support
[UI] Fixes add account dialogs
[UI] Deleted the hint about several XMPP provider
[LOG] changed logging files
```

**Comment by AbdBarho** [comment]
after adding the html whiteboard, the old one might break because it cannot render certain shapes, of course I patched the old whiteboard to avoid breaking, but should that be mentioned?

If user A has updated saros and is using the html wb, but user B is still using an old version of saros, then the whiteboard on user B's machine will break.

also how can I determine whether HTML Whiteboard is already deliverable ? it works?

**Comment by m273d15** [comment]
I would prefer to ship only the HTML whiteboard and remove the old one. Maintaining two versions is not reasonable . If the HTML-WB **works with Windows and Linux** (and if you can test it with Mac) I see no reason why we should not use the HTML WB.

If we deliver the HTML WB, we also have to adjust the changelog and also mention the reimplementation in the release note.

**Comment by m273d15** [comment]
@srossbach Could you explain in more detail (probably in a separate issue) what we have to do to `Rework ColorIDSet and XMPPAccount serialization` and why this is a prerequisite for a release?

**Comment by srossbach** [comment]
Because every time we change package names the saved data is lost. And if I am not wrong the internal Java class serialization is already deprecated. We also have to ensure that the account data is converted correctly or do you think that the user enjoy an empty account store after an update ?
