### ISSUE TITLE
Stop work on the HTML-GUI

### ISSUE THREAD

**Issue by m273d15** [saros-project/saros#682]
Based on the issues with the integration of the HTML-GUI (I will describe them in the documentation mentioned below) we decided that we don't want to invest more work into the HTML-GUI approach and rather implement native ide specific GUIs.

We have to perform the following steps:
- [x] Create documentation about the approach and reasons why we stopped working on it (#695)
- [x] Remove `ui.frontend` (the HTML-GUI code) (#695) and document the last commit with the HTML-GUI in the documentation
- [x] Remove `ui` and move `saros.ui.util` content into core (#695)
- [x] Remove HTML-GUI from CI process (#695)
- [x] Close HTML-GUI related issues and reference the documentation
- [x] Remove HTML-GUI related issue label
- [ ] Either remove the HTML-Whiteboard, remove the HTML-Whiteboard CI process or just keep it. *Decision:* Keep both implementations and perform further user tests in order to clarify the current state of the whiteboard development.

**Comment by srossbach** [comment]
I have not tried out the HTML-Whiteboard yet (is there any way to download the generated html and js files ?) but I do not think that if it works fine we should remove it. Just let the user decide which one to use or is the HTML whiteboard not compatible with the standard whiteboard. I guess they should because they only generate and process SXE records.

**Comment by m273d15** [comment]
The HTML-Whiteboard has the same issue as the HTML-GUI. The integration of a browser into eclipse. The current implementation uses the SWTBrowse. The javascript implementation is fine, the basic java synchronization has some issues (closing the whiteboard view cuts the connection in one direction), but this is not HTML-WB related.

> Just let the user decide which one to use or is the HTML whiteboard not compatible with the standard whiteboard. I guess they should because they only generate and process SXE records.

I think they are compatible.

> is there any way to download the generated html and js files

The only way is to build the files locally via npm. There is no public release.
