### ISSUE TITLE
Minor issues with website

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#687]
As partly mentioned in #672, there are still some minor issues with the website, introduced with the tab system.

- [x] ~~Icons have a wrong vertical offset in tabs (see [eclipse getting started page](https://www.saros-project.org/documentation/getting-started.html?tab=eclipse#step-5-exploring-the-saros-toolbar))~~ Fixed with #756.
- [x] ~~Lists have an empty line when a new level starts in tabs (see [intellij getting started page](https://www.saros-project.org/documentation/getting-started.html?tab=intellij#features))~~ Fixed with #756.
- [x] ~~Broken link <https://www.saros-project.org/contribute/development-environment.html> of clean-up profile xml~~ Fixed with #761.
- [x] ~~Some images don't scale correctly on mobile, breaking the side width. See [getting started - eclipse](https://www.saros-project.org/documentation/getting-started.html?tab=eclipse#step-1-connecting)~~ Workaround for remaining images added with #770.
- [x] ~~#571~~ 
- [ ] TOC and nav-bar always stay on top of the page and no longer scroll along with the current view
- [ ] Nav-bar sub-menu close when any entry besides the last is selected (see [intellij release 0.2.0](https://www.saros-project.org/releases/saros-i_0.2.0.html) for closed, [intellij release 0.1.0](https://www.saros-project.org/releases/saros-i_0.1.0.html) for open).

Optional:
- [ ] Some eclipse icons don't have a transparent background (see [eclipse getting started page](https://www.saros-project.org/documentation/getting-started.html?tab=eclipse#step-5-exploring-the-saros-toolbar))

**Comment by tobous** [comment]
Added new issue about nav-bar sub-menues.
